def menu():
    print('***********************************************************')
    print('*        Bem Vindo ao Sistema de Boletim Escolar          *')
    print('***********************************************************')
    print('*              1 - Matricular Aluno                       *')
    print('*              2 - Listar Todos os Alunos                 *')
    print('*              3 - Listar Alunos Aprovados                *')
    print('*              4 - Listar Aluno de Recuperação            *')
    print('*              5 - Listar Aluno Reprovados                *')
    print('*              6 - Buscar Aluno por Nome                  *')
    print('*              7 - Buscar Aluno por Matricula             *')
    print('*              8 - Excluir Aluno                          *')
    print('*              9 - Lançar Notas                           *')
    print('*              10- Listar Notas                           *')
    print('*              11- Excluir Notas                          *')
    print('*              12- Sair                                   *')
    print('*                                                         *')
    print('***********************************************************')